apiVersion: apps/v1
kind: Deployment
metadata:
  name: truffle-ai-deployment
  annotations:
    kubernetes.io/change-cause: <CHANGE-CAUSE>
  labels:
    app: truffle-ai-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truffle-ai-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: truffle-ai-deployment
    spec:
      containers:
        - name: truffle-ai-graphql-gateway
          image: <GRAPHQL-GATEWAY-IMAGE>
          ports:
            - containerPort: <GRAPHQL-GATEWAY-PORT>
          envFrom:
            - configMapRef:
                name: graphql-gateway-config
            - secretRef:
                name: graphql-gateway-secret
        - name: truffle-ai-graphql-server
          image: <GRAPHQL-SERVER-IMAGE>
          ports:
            - containerPort: <GRAPHQL-SERVER-PORT>
          envFrom:
            - configMapRef:
                name: graphql-server-config
            - secretRef:
                name: graphql-server-secret
---
apiVersion: v1
kind: Service
metadata:
  name: truffle-ai-load-balancer
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: 'truffle-ai-load-balancer'
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: '<CERTIFICATE-ID>'
    service.beta.kubernetes.io/do-loadbalancer-protocol: 'https'
    service.beta.kubernetes.io/do-loadbalancer-size-unit: '1'
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: 'true'
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: 'true'
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: <GRAPHQL-GATEWAY-PORT>
    - name: https
      protocol: TCP
      port: 443
      targetPort: <GRAPHQL-GATEWAY-PORT>
  selector:
    app: truffle-ai-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: truffle-ai-graphql-server-service
spec:
  selector:
    app: truffle-ai-deployment
  ports:
    - name: graphql-server
      protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: truffle-ai-repo-cronjob
spec:
  timeZone: 'Europe/Berlin'
  # Todo: change minutes back to 0
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: truffle-ai-repo-cronjob
              image: <REPO-JOB-IMAGE>
              envFrom:
                - configMapRef:
                    name: repo-job-config
                - secretRef:
                    name: repo-job-secret
          restartPolicy: OnFailure
